apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpecho
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tcpecho
    spec:
      containers:
      - name: tcpecho
        image: dseeley/tcpecho:1.0.1
        ports:
        - containerPort: 3495
